# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly"
# https://rust-lang.github.io/rustup/concepts/components.html
components = ["rustc", "cargo", "rustfmt", "rust-analyzer", "clippy"]
profile = "minimal"
