[rust]
lld = true

# x86_64-unknown-linux-gnu (lld)
# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(all())']
rustflags = [
    # UUID Unstable for Uuid::now_v7()
    # https://docs.rs/uuid/1.4.0/uuid/index.html#unstable-features
    "--cfg",
    "uuid_unstable",
    # Tokio Unstable for `console` feature
    # https://github.com/tokio-rs/console#instrumenting-your-program
    "--cfg",
    "tokio_unstable",
]

# x86_64-v3 (Intel Haswell / AMD Excavator and above)
# https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=x86-64-v3"]

# aarch64 (ARM Neon)
[target.'cfg(target_arch = "aarch64")']
rustflags = ["-C", "target-feature=+neon"]
