[rust]
lld = true

[build]
rustflags = [
    # UUID Unstable for Uuid::now_v7()
    # https://docs.rs/uuid/1.4.0/uuid/index.html#unstable-features
    "--cfg",
    "uuid_unstable",
    # Tokio Unstable for `console` feature
    # https://github.com/tokio-rs/console#instrumenting-your-program
    "--cfg",
    "tokio_unstable",
]
