//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::activity::Entity as Activity;
pub use super::post::Entity as Post;
pub use super::user::Entity as User;
pub use super::user_follower::Entity as UserFollower;
