//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_feed")]
pub struct Model {
    pub user_id: String,
    pub hatsu: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub feed_url: String,
    pub next_url: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub language: Option<String>,
    pub items: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
