//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::{
    activity::Entity as Activity,
    blocked_url::Entity as BlockedUrl,
    post::Entity as Post,
    received_announce::Entity as ReceivedAnnounce,
    received_follow::Entity as ReceivedFollow,
    received_like::Entity as ReceivedLike,
    user::Entity as User,
    user_feed_item::Entity as UserFeedItem,
};
