//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::{
    activity::Entity as Activity,
    post::Entity as Post,
    received_announce::Entity as ReceivedAnnounce,
    received_follow::Entity as ReceivedFollow,
    received_like::Entity as ReceivedLike,
    user::Entity as User,
    user_feed_item::Entity as UserFeedItem,
};
